url: https://visalisa.github.io/

# Site settings
title: "Lisa Jiamsirioungkul"
email: visakhalisajiam@gmail.com
description: "Product Manager"


# Team names, titles and social links
people:
- name: Lisa Jiamsirioungkul  
  pic: 1
  social:
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/visalisago
  - title: github
    url: https://github.com/visalisa
  - title: linkedin
    url: https://www.linkedin.com/in/visalisa
  - title: instagram
    url: https://www.instagram.com/visalisa

# Postal address (add as many lines as necessary)
address:
  - line: Seatlle, WA

footer:
  copyright: VisaLisa
  location: Seattle, WA
  social: Everywhere
  credits: Credits

# Credits content
credits: https://github.com/y7kim/agency-jekyll-theme

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
